  
name: Test_Artifact_V2
on: [push]
jobs:
  v2-artifacts:
    runs-on: [ubuntu-latest]
    env:
      name: my-artifact-name
    steps:
    - uses: actions/checkout@v2
        
    - run: |	
        mkdir download-dir1	
        mkdir download-dir2	
        touch node_modules/empty	
    - name: 'Upload artifact using v1'		
      uses: actions/upload-artifact@v1	
      with:		
        name: 'V1-Artifact-Upload'	
        path: node_modules/	

    - name: 'Download artifact using v2'		
      uses: konradpabjan/download-artifact@v2-preview	
      with:		
        name: 'V1-Artifact-Upload'	
        path: download-dir1	

    - name: 'Upload artifact using v2'		
      uses: konradpabjan/upload-artifact@v2-preview	
      with:		
        name: 'V2-Artifact-Upload'	
        path: download-dir1	

    - name: 'Download artifact using v1'		
      uses: actions/download-artifact@v1	
      with:		
        name: 'V2-Artifact-Upload'	
        path: download-dir2
